# This workflow is to build AI Glass examples and upload the binary file as an artifact.
# It is triggered on push or pull request events that modify the specified files or directories.
# It also allows manual triggering via workflow_dispatch.

name: Build AI Glass Examples

on:
  # push:
  #   branches:
  #     - 'main'
  #   paths:
  #     - '.github/workflows/CI-compile-aiglass-examples.yml'
  #     - '.github/scripts/python/compile-aiglass-examples.py'
  #     - '.github/scripts/python/bootstrap-linux-env.py'
  #     - '.github/scripts/python/bootstrap-macos-env.py'
  #     - 'project/realtek_amebapro2_v0_example/scenario/ai_glass/**'
  # pull_request:
  #   paths:
  #     - '.github/workflows/CI-compile-aiglass-examples.yml'
  #     - '.github/scripts/python/compile-aiglass-examples.py'
  #     - '.github/scripts/python/bootstrap-linux-env.py'
  #     - '.github/scripts/python/bootstrap-macos-env.py'
  #     - 'project/realtek_amebapro2_v0_example/scenario/ai_glass/**'
  
  workflow_dispatch:

jobs:
  build-examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bootstrap Linux Environment
        if: runner.os == 'Linux'
        run: python3 .github/scripts/python/bootstrap-linux-env.py

      - name: Bootstrap MacOS Environment
        if: runner.os == 'macOS'
        run: python3 .github/scripts/python/bootstrap-macos-env.py

      - name: Grant execute permission to all mp tools executable (Linux)
        if: runner.os == 'Linux'
        run: chmod +x project/realtek_amebapro2_v0_example/GCC-RELEASE/mp/*.linux || true
      
      - name: Grant execute permission to all mp tools executable (macOS)
        if: runner.os == 'macOS'
        run: chmod +x project/realtek_amebapro2_v0_example/GCC-RELEASE/mp/*.darwin || true

      - name: Run build script on ${{ runner.os }}
        if: runner.os != 'Windows'
        run: python3 .github/scripts/python/compile-aiglass-examples.py

      - name: Build complete
        run: echo "Build finished."
      
      # - name: Upload modified source files
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: modified-sources
      #     path: |
      #       component/file_system/fatfs/fatfs_sdcard_api.c
      #       component/media/mmfv2/module_mp4.c
      #       component/soc/8735b/misc/platform/user_boot.c
      #       component/video/driver/RTL8735B/video_user_boot.c
      #       project/realtek_amebapro2_v0_example/inc/sensor.h

      # Upload binary file to GitHub Artifacts
      - name: Upload binary file
        uses: actions/upload-artifact@v4
        with:
          name: aiglass-example-${{ matrix.os }}
          path: project/realtek_amebapro2_v0_example/GCC-RELEASE/build/flash_ntz.bin